version: "3"
name: cdsp-waii-iotdb

services:

# Apache IoTDB acting as VSS Data Store
  iotdb-service:
    image: apache/iotdb:1.2.2-standalone
    hostname: iotdb-service
    container_name: iotdb-service

# WAII acting as VISS Protocol Data Server
  waii-service:
    hostname: waii-service
    container_name: waii-service
