version: "3"
name: cdsp-waii-iotdb

services:

# Apache IoTDB acting as VSS Data Store
  iotdb-service:
    image: apache/iotdb:1.2.2-standalone
    hostname: iotdb-service
    container_name: iotdb-service

# WAII acting as VISS Protocol Data Server
  tmp:
    image: busybox
    container_name: waii_container_volumes
    user: root
    command: >
      chmod -R 777 /tmp/docker/
    volumes:
      - /tmp/docker/

  redis:
    image: redis
    container_name: app_redis
    privileged: true
    user: root
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis/redis.conf:/etc/redis.conf
    volumes_from:
      - tmp

  vissv2server:
    container_name: vissv2server
    build:
      context: .  # context set to repo root
      target: vissv2server
    entrypoint: [ /app/vissv2server,-s,redis]
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:8887:8887"
    volumes:
      - ./logs:/app/logs
    volumes_from:
      - tmp
